package com.yuanlai.wpnos.ylcmsb.dao;


import com.yuanlai.wpnos.ylcmsb.model.SeqNo;

public interface SeqNoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_seqrec_inf
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    int deleteByPrimaryKey(String keynam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_seqrec_inf
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    int insert(SeqNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_seqrec_inf
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    int insertSelective(SeqNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_seqrec_inf
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    SeqNo selectByPrimaryKey(String keynam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_seqrec_inf
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    int updateByPrimaryKeySelective(SeqNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_seqrec_inf
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    int updateByPrimaryKey(SeqNo record);
}