package com.yuanlai.wpnos.ylcmsb.entity;

import java.io.Serializable;

public class CateringDish implements Serializable {

    private String dishImage;
    private String dishImage2;
    private String dishDes;

    public String getDishDes() {
		return dishDes;
	}

	public void setDishDes(String dishDes) {
		this.dishDes = dishDes;
	}

	public String getDishImage() {
        return dishImage;
    }

    public void setDishImage(String dishImage) {
        this.dishImage = dishImage;
    }

    public String getDishImage2() {
		return dishImage2;
	}

	public void setDishImage2(String dishImage2) {
		this.dishImage2 = dishImage2;
	}

	private String createTime;
    private String modifyTime;

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.dish_id
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.dish_name
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String dishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.dishes_id
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String dishesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.in_stock
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String inStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.price
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.discount_price
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catering_dish.enabled
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catering_dish
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.dish_id
     *
     * @return the value of catering_dish.dish_id
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.dish_id
     *
     * @param dishId the value for catering_dish.dish_id
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setDishId(String dishId) {
        this.dishId = dishId == null ? null : dishId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.dish_name
     *
     * @return the value of catering_dish.dish_name
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getDishName() {
        return dishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.dish_name
     *
     * @param dishName the value for catering_dish.dish_name
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setDishName(String dishName) {
        this.dishName = dishName == null ? null : dishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.dishes_id
     *
     * @return the value of catering_dish.dishes_id
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getDishesId() {
        return dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.dishes_id
     *
     * @param dishesId the value for catering_dish.dishes_id
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setDishesId(String dishesId) {
        this.dishesId = dishesId == null ? null : dishesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.in_stock
     *
     * @return the value of catering_dish.in_stock
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getInStock() {
        return inStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.in_stock
     *
     * @param inStock the value for catering_dish.in_stock
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setInStock(String inStock) {
        this.inStock = inStock == null ? null : inStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.price
     *
     * @return the value of catering_dish.price
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.price
     *
     * @param price the value for catering_dish.price
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.discount_price
     *
     * @return the value of catering_dish.discount_price
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.discount_price
     *
     * @param discountPrice the value for catering_dish.discount_price
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setDiscountPrice(String discountPrice) {
        this.discountPrice = discountPrice == null ? null : discountPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catering_dish.enabled
     *
     * @return the value of catering_dish.enabled
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catering_dish.enabled
     *
     * @param enabled the value for catering_dish.enabled
     *
     * @mbggenerated Fri Jun 30 15:07:37 CST 2017
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }
}