package com.yuanlai.wpnos.ylcmsb.entity;

import java.io.Serializable;

public class Store implements Serializable {
    private String storeStatus;
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.branch_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_address
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String storeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_image
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String storeImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.cuisine_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String cuisineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.moblie_no
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String moblieNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.per_capita_price
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String perCapitaPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.service_info
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String serviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.special_service
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String specialService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.recommend
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.introduction
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.business_hours
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String businessHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.create_time
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.modify_time
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.treeCode
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private String treeCode;

    public String getTreeCode() {
        return treeCode;
    }

    public void setTreeCode(String treeCode) {
        this.treeCode = treeCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table store
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_id
     *
     * @return the value of store.store_id
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_id
     *
     * @param storeId the value for store.store_id
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_name
     *
     * @return the value of store.store_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_name
     *
     * @param storeName the value for store.store_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.branch_name
     *
     * @return the value of store.branch_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.branch_name
     *
     * @param branchName the value for store.branch_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_address
     *
     * @return the value of store.store_address
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_address
     *
     * @param storeAddress the value for store.store_address
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress == null ? null : storeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_image
     *
     * @return the value of store.store_image
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getStoreImage() {
        return storeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_image
     *
     * @param storeImage the value for store.store_image
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setStoreImage(String storeImage) {
        this.storeImage = storeImage == null ? null : storeImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.cuisine_name
     *
     * @return the value of store.cuisine_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getCuisineName() {
        return cuisineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.cuisine_name
     *
     * @param cuisineName the value for store.cuisine_name
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setCuisineName(String cuisineName) {
        this.cuisineName = cuisineName == null ? null : cuisineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.moblie_no
     *
     * @return the value of store.moblie_no
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getMoblieNo() {
        return moblieNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.moblie_no
     *
     * @param moblieNo the value for store.moblie_no
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setMoblieNo(String moblieNo) {
        this.moblieNo = moblieNo == null ? null : moblieNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.per_capita_price
     *
     * @return the value of store.per_capita_price
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getPerCapitaPrice() {
        return perCapitaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.per_capita_price
     *
     * @param perCapitaPrice the value for store.per_capita_price
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setPerCapitaPrice(String perCapitaPrice) {
        this.perCapitaPrice = perCapitaPrice == null ? null : perCapitaPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.service_info
     *
     * @return the value of store.service_info
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getServiceInfo() {
        return serviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.service_info
     *
     * @param serviceInfo the value for store.service_info
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setServiceInfo(String serviceInfo) {
        this.serviceInfo = serviceInfo == null ? null : serviceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.special_service
     *
     * @return the value of store.special_service
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getSpecialService() {
        return specialService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.special_service
     *
     * @param specialService the value for store.special_service
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setSpecialService(String specialService) {
        this.specialService = specialService == null ? null : specialService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.recommend
     *
     * @return the value of store.recommend
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.recommend
     *
     * @param recommend the value for store.recommend
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend == null ? null : recommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.introduction
     *
     * @return the value of store.introduction
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.introduction
     *
     * @param introduction the value for store.introduction
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.business_hours
     *
     * @return the value of store.business_hours
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getBusinessHours() {
        return businessHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.business_hours
     *
     * @param businessHours the value for store.business_hours
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setBusinessHours(String businessHours) {
        this.businessHours = businessHours == null ? null : businessHours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.create_time
     *
     * @return the value of store.create_time
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.create_time
     *
     * @param createTime the value for store.create_time
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.modify_time
     *
     * @return the value of store.modify_time
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.modify_time
     *
     * @param modifyTime the value for store.modify_time
     *
     * @mbggenerated Wed Jun 28 15:04:08 CST 2017
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

	public String getStoreStatus() {
		return storeStatus;
	}

	public void setStoreStatus(String storeStatus) {
		this.storeStatus = storeStatus;
	}
    
}