package com.yuanlai.wpnos.ylcmsb.model;

public class SeqNo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_seqrec_inf.KEYNAM
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    private String keynam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_seqrec_inf.KEYVAL
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    private String keyval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_seqrec_inf.KEYNAM
     *
     * @return the value of pub_seqrec_inf.KEYNAM
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    public String getKeynam() {
        return keynam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_seqrec_inf.KEYNAM
     *
     * @param keynam the value for pub_seqrec_inf.KEYNAM
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    public void setKeynam(String keynam) {
        this.keynam = keynam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_seqrec_inf.KEYVAL
     *
     * @return the value of pub_seqrec_inf.KEYVAL
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    public String getKeyval() {
        return keyval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_seqrec_inf.KEYVAL
     *
     * @param keyval the value for pub_seqrec_inf.KEYVAL
     *
     * @mbg.generated Tue May 23 14:34:40 CST 2017
     */
    public void setKeyval(String keyval) {
        this.keyval = keyval;
    }
}